app2/urls.py
from django.urls import path
from app2.views import *
app_name='gowtham_01'
urlpatterns=[
    path("gowtham1/",gowtham1,name='gowtham1'),
]

project10/urls.py
from django.contrib import admin
from django.urls import path,include
from app1.views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path("gowtham/",gowtham,name='gowtham'),
    path("app2/",include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def gowtham (request):
    return render(request,'01.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def gowtham1 (request):
    return render(request,'02.html')

templates/01.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1><i>My Name Is Gowtham I am From Nellore</i></h1>
        <a href="{% url 'gowtham_01:gowtham1' %}">go to click</a>
    </center>
</body>
</html>

templates/02.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1><i>I Lern PYTHON Full Stack Developer In Jspiders Marathahalli Banglore </i></h1>
        <a href="{% url 'gowtham' %}">goto click</a>
    </center>
</body>
</html>